# Generated by Django 5.1.4 on 2024-12-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pimage', models.ImageField(upload_to='projects/')),
                ('pdesc', models.TextField()),
            ],
        ),
    ]
