# Generated by Django 5.1.4 on 2024-12-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='github',
        ),
        migrations.RemoveField(
            model_name='home',
            name='linkdn',
        ),
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
